name: saveplus_plus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FlutterFire
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

  # State mgmt, HTTP, Map, Icons
  provider: ^6.1.3
  http: ^1.4.0
  google_maps_flutter: ^2.5.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.8
  
  # Charts and Visualizations
  fl_chart: ^1.0.0
  
  # Date and Time
  intl: ^0.18.1
  table_calendar: ^3.0.9
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Location Services (NO API KEY REQUIRED)
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true