// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJazCzR2CS7eWZQ_wPCpnQxwurJ1IfBOo',
    appId: '1:374152583687:web:da924fd83e686adf2468a2',
    messagingSenderId: '374152583687',
    projectId: 'saveplus-plus',
    authDomain: 'saveplus-plus.firebaseapp.com',
    storageBucket: 'saveplus-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByzLkt4U8FLpIGxbNAvstreOwLKE0dVXA',
    appId: '1:374152583687:android:11fe2fd9138cd56e2468a2',
    messagingSenderId: '374152583687',
    projectId: 'saveplus-plus',
    storageBucket: 'saveplus-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7MOHL4TzikgqEdv8-U1sxr9vNq51B-U0',
    appId: '1:374152583687:ios:1e6aeee41a4a25c62468a2',
    messagingSenderId: '374152583687',
    projectId: 'saveplus-plus',
    storageBucket: 'saveplus-plus.firebasestorage.app',
    iosBundleId: 'com.example.saveplusPlusv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7MOHL4TzikgqEdv8-U1sxr9vNq51B-U0',
    appId: '1:374152583687:ios:1e6aeee41a4a25c62468a2',
    messagingSenderId: '374152583687',
    projectId: 'saveplus-plus',
    storageBucket: 'saveplus-plus.firebasestorage.app',
    iosBundleId: 'com.example.saveplusPlusv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJazCzR2CS7eWZQ_wPCpnQxwurJ1IfBOo',
    appId: '1:374152583687:web:20e447d852a709532468a2',
    messagingSenderId: '374152583687',
    projectId: 'saveplus-plus',
    authDomain: 'saveplus-plus.firebaseapp.com',
    storageBucket: 'saveplus-plus.firebasestorage.app',
  );

}